# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac7427b0a91da8b96bfb1f6da9f57553af9440fd056efdf558e3218901b3305140e70cfca4021beed06fc3ee2ec8c63f76649a4319b2c1773dc6ae164e720abd

test:
  secret_key_base: f1deb8659a1ee7c5b126fcea32b265d39bdc5f9f76bc9b72d7ce328aa5ef74181b3437cb96c450fa3e8a76aa2f51b5bb46a2a1a8ea69097f52d471010b03f504

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
